sudo: required
services:
  - docker

before_install:
  - docker build -t nfhbar/server-template -f Dockerfile.dev .

script:
  - docker run nfhbar/server-template npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "server-template"
  env: "ServerTemplate-env"
  bucket_name: "elasticbeanstalk-us-east-2-259280065187"
  bucket_path: "server-template"
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_ACCESS_SECRET"
